### ISSUE TITLE
Is it possible to combine the benefits of both versions?

### ISSUE THREAD

**Issue by uzvervolf** [AntoshVik/ETHBreaker#3]
The first version is almost perfect. It is easily customizable: it has the ability to specify the salt and the complexity of the wallet. The only serious drawback is the balance check through infura. 
The advantage of the second version is the ability to specify the number of childrens and check the balance through mewapi with the ability to specify a proxy.

It seems to me that if you add a balance check through mewapi with a proxy and add childrens to the first version, then it will be much more efficiently.

Such a variant could be called the final third version. Could you do it? Or is it impossible?

**Comment by AntoshVik** [comment]
Version 1.5 realeased for you
